POST http://localhost:3333/videos
Content-type: application/json

{
  "title": "Testando console log",
  "description": "Foi inserido o console log para teste de CRUD",
  "duration": 300
}

### 

GET http://localhost:3333/videos?search=node

### 

GET http://localhost:3333/videos

### 

PUT http://localhost:3333/videos/2c230c8a-deb2-42e9-a56f-596b9c6f7499
Content-type: application/json

{
  "title": "Video Alterado",
  "description": "Alterando infos do video video",
  "duration": 420
}

### 

DELETE http://localhost:3333/videos/47058251-f048-464c-9237-baee6581ffba